#!/bin/sh -e
# $Id: postinst,v 1.3 2001/09/06 22:34:37 elf Exp $
#
# postinst for buici-clock

# Remove detritus
if test -f /usr/X11R6/share/man/man1/buici-clock.1.gz ; then rm /usr/X11R6/share/man/man1/buici-clock.1.gz ; fi

#DEBHELPER#
